In [4]:
from autogc_validation.workspace.files import rename_dattxt_files_to_txt
from pathlib import Path
week_folder = Path(r"D:\LP\LP202511v1\FINAL\week 4")
output_folder = week_folder / "MAX upload"
files_renamed = rename_dattxt_files_to_txt(week_folder, output_folder)
print(f"Renamed {files_renamed['written']} file(s), {files_renamed['overwritten']} overwritten")

Renamed 1 file(s), 1 overwritten

In [7]:
from autogc_validation.reports.aqs import compare_aqs_to_dataset
from aqs_tools.processors import summarize_nulls_by_hour, summarize_qualifiers_by_hour, summarize_nulls_by_compound, summarize_qualifiers_by_compound
import pandas as pd
aqs_file = r"D:\LP\LP202512v1\AQS\RD_SITE-LP_LakePark_INSERT_12-01-2025_to_12-31-2025 (2).txt"  # ← set path to AQS RD upload file


nbh = summarize_nulls_by_hour(aqs_file, "RD", threshold = 34)
display(nbh)
qbh = summarize_qualifiers_by_hour(aqs_file, "RD", threshold = 34)
display(qbh)
pd.set_option('display.max_columns', None)
nbc = summarize_nulls_by_compound(aqs_file, "RD")
nbc_df = pd.DataFrame(nbc)
display(nbc_df)

qbc = summarize_qualifiers_by_compound(aqs_file, "RD")
qbc_df = pd.DataFrame(qbc)
display(qbc_df)

{'AQ': 5,
 'AS': 0,
 'AT': 4,
 'AY': 75,
 'BH': 1,
 'DA': 1,
 'TC': 4,
 'XX': 1,
 'total': 91}

{'EH': 0, 'LB': 0, 'LJ': 0, 'MD': 84, 'ND': 0, 'QX': 0, 'SQ': 0, 'total': 84}

,43102,43141,43202,43203,43204,43205,43206,43212,43214,43216,43217,43218,43220,43221,43224,43226,43227,43230,43231,43232,43233,43235,43238,43242,43243,43244,43245,43247,43248,43249,43250,43252,43253,43261,43262,43263,43280,43284,43285,43291,43954,43960,45109,45201,45202,45203,45204,45207,45208,45209,45210,45211,45212,45213,45218,45219,45220,45225
AQ,5.0,5.0,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
AT,4.0,4.0,4,NaN,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
AY,75.0,75.0,70,61.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0,75.0
BH,1.0,1.0,1,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
DA,1.0,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
TC,4.0,4.0,3,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
XX,1.0,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
no_null,653.0,653.0,612,549.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,652.0,653.0,653.0,653.0,653.0,653.0,653.0,652.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0,653.0
total,744.0,744.0,744,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0
AS,NaN,NaN,47,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,43102,43141,43202,43203,43204,43205,43206,43212,43214,43216,43217,43218,43220,43221,43224,43226,43227,43230,43231,43232,43233,43235,43238,43242,43243,43244,43245,43247,43248,43249,43250,43252,43253,43261,43262,43263,43280,43284,43285,43291,43954,43960,45109,45201,45202,45203,45204,45207,45208,45209,45210,45211,45212,45213,45218,45219,45220,45225
no_qualifier,744.0,0.0,339.0,43.0,724.0,547.0,0.0,732.0,743.0,291.0,628.0,313.0,730.0,736.0,340.0,298.0,258.0,535.0,592.0,294.0,316.0,300.0,340.0,350.0,308.0,351.0,0.0,351.0,284.0,437.0,540.0,427.0,273.0,404.0,406.0,443.0,401.0,403.0,668.0,426.0,245.0,423.0,450.0,536.0,689.0,397.0,518.0,318.0,211.0,105.0,92.0,282.0,376.0,296.0,0.0,0.0,268.0,238.0
total,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0,744.0
LJ,NaN,744.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,168.0,NaN,NaN,NaN,NaN,NaN,NaN,168.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,744.0,NaN,NaN
MD,NaN,431.0,1.0,2.0,1.0,10.0,6.0,NaN,NaN,311.0,NaN,198.0,2.0,4.0,143.0,376.0,420.0,17.0,4.0,321.0,280.0,315.0,270.0,234.0,330.0,202.0,381.0,59.0,308.0,150.0,36.0,95.0,344.0,166.0,50.0,76.0,27.0,150.0,6.0,109.0,344.0,8.0,25.0,NaN,1.0,130.0,36.0,281.0,357.0,470.0,536.0,312.0,148.0,304.0,595.0,656.0,359.0,376.0
ND,NaN,70.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,129.0,116.0,46.0,2.0,1.0,11.0,212.0,324.0,1.0,NaN,1.0,12.0,55.0,85.0,63.0,192.0,49.0,164.0,14.0,53.0,3.0,6.0,13.0,28.0,11.0,23.0,3.0,2.0,18.0,3.0,13.0,82.0,1.0,NaN,NaN,1.0,NaN,2.0,76.0,4.0,110.0,250.0,148.0,5.0,80.0,342.0,151.0,175.0,133.0
SQ,NaN,190.0,NaN,15.0,NaN,187.0,78.0,NaN,NaN,142.0,116.0,205.0,12.0,NaN,261.0,70.0,66.0,192.0,148.0,129.0,148.0,129.0,134.0,160.0,106.0,191.0,167.0,251.0,152.0,157.0,167.0,222.0,127.0,174.0,204.0,194.0,316.0,191.0,70.0,209.0,155.0,313.0,216.0,37.0,49.0,217.0,190.0,145.0,120.0,166.0,116.0,150.0,220.0,144.0,61.0,NaN,117.0,130.0
EH,NaN,NaN,79.0,3.0,19.0,NaN,NaN,12.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LB,NaN,NaN,399.0,699.0,NaN,NaN,355.0,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,68.0,171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QX,NaN,NaN,143.0,NaN,NaN,NaN,744.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.0,47.0,NaN,NaN,NaN,NaN,NaN,744.0,NaN,NaN

In [3]:
  import autogc_validation.workspace
  print(autogc_validation.workspace.__file__)

C:\Users\aengstrom\Documents\Python\autogc_validation\src\autogc_validation\workspace\__init__.py